#ifndef __MM_STAT_MACRO_H__
#define __MM_STAT_MACRO_H__


#define CONFIG_ADC_MEMCG 1
// #define PROFILE_MADV_FREE_BREAKDOWN 1

#define BYPASS_SWAP_GARBAGE 1
#define ADC_ADVISE_FREE_BYPASS_ALLOC_SWAP_ENTRY 1
#ifdef ADC_ADVISE_FREE_BYPASS_ALLOC_SWAP_ENTRY
    #define ADC_ADVISE_SWAPOUT_SKIP_WALK_RMAP_FOR_UNMAP 1
#endif

#endif